name: apppelanggaran
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1       # Untuk State Management (ViewModel)
  http: ^1.2.0           # Untuk komunikasi dengan API PHP
  shared_preferences: ^2.2.2  # Untuk fitur "Ingat Saya" (menyimpan token)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
